<a href="https://colab.research.google.com/github/Nomadnp21/GITpract/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
a=np.array(lst)

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [8]:
a1=np.array([[4,5,8],[7,8,9]])

In [9]:
a1.shape

(2, 3)

In [10]:
a1.reshape(1,6)

array([[4, 5, 8, 7, 8, 9]])

In [11]:
np.array((1,2,3,4,5,6))

array([1, 2, 3, 4, 5, 6])

In [14]:
n1=np.arange(1,10,2)

In [15]:
n1.reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [16]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [18]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
print('Random number generation(uniform distribution)')
np.random.rand(2,3)

Random number generation(uniform distribution)


array([[0.730362  , 0.40719592, 0.66368828],
       [0.50286491, 0.96400754, 0.89829794]])

In [24]:
print('random number following normal distribution with mean=0 and std=1')
print(np.random.randn(5,3))

random number following normal distribution with mean=0 and std=1
[[ 0.10617386  0.07712006  0.85185419]
 [-0.3419729   1.0495544  -1.08316281]
 [ 0.66128136  0.30531918  2.45262424]
 [-1.09261485  0.51555092 -0.11491717]
 [ 1.03436843 -0.0184896  -0.21045309]]


In [25]:
np.random.randint(1,100)

43

In [26]:
np.random.randint(1,100,(4,4))

array([[66,  5, 67, 14],
       [40, 32, 98, 90],
       [17, 84, 81, 55],
       [97, 95, 10, 32]])

In [27]:
arr=np.arange(0,11)

In [28]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
ar=np.random.randint(2,100,20).reshape(5,4)

In [30]:
ar

array([[11, 74, 91,  2],
       [57, 90,  9, 59],
       [ 6,  6, 96, 15],
       [ 8, 71, 42, 67],
       [94, 25, 69, 39]])

In [31]:
ar[0:4]

array([[11, 74, 91,  2],
       [57, 90,  9, 59],
       [ 6,  6, 96, 15],
       [ 8, 71, 42, 67]])

In [32]:
ar[0:3,0:3]

array([[11, 74, 91],
       [57, 90,  9],
       [ 6,  6, 96]])

In [ ]:
a